### ISSUE TITLE
Enju仮想マシンのログインIDとパスワードって？

### ISSUE THREAD

**Issue by yegusa** [next-l/manual#1]
12/21 のEnju開発WSで作ったマニュアル用のEnju仮想マシン
http://www.next-l.jp/download/vm/enju_leaf_ws_1.1.0.rc7_virtualbox.zip

を起動したときに、入力が必要な
ログインIDとパスワードってなんですか？

**Comment by nakamura-akifumi** [comment]
ID、パスワード ともに、vagrant で出来るかと思います。

**Comment by yegusa** [comment]
ログインできました！ありがとうございます。
