### ISSUE TITLE
マニュアル用Enju仮想マシン（VirtualBox）の作成・アップロード

### ISSUE THREAD

**Issue by yegusa** [next-l/manual#3]
ちゃんとした（？）マニュアル用Enju仮想マシン（VirtualBox）の作成・アップロード

「Next-L Enju インストールマニュアル（VirtualBox編）」 の第一稿をつくっちゃいたいので、
とりいそぎ、やってもらえるとうれしいな。

**Comment by nakamura-akifumi** [comment]
中村の分は、土曜日に作業出来そうなんで、その日に送れるようにします。

**Comment by yegusa** [comment]
いま、メニューをガンガンかえちゃってるから、Next-L Enju Leaf 1.1.0.rc10になったらあたらしい仮想マシンつくりましょうかねえ。そのときは @nakamura-akifumi  さん、よろしくです。

**Comment by yegusa** [comment]
これ、Enju WS で、rcレベルはまあ、いっかってことになったのでクローズします。
