### ISSUE TITLE
アプリケーションの画面からマニュアルへのリンクを張る：enju_leafへ移動

### ISSUE THREAD

**Issue by nabeta** [next-l/manual#30]
検索や貸出など、それぞれの画面で、対応するマニュアル項目へのリンクを追加したいです。

**Comment by yegusa** [comment]
→　こちらは、マニュアルというよりは enju_leaf の機能ですので、

https://github.com/next-l/enju_leaf/issues/244

へ　移動します。

のでこちらはいったんクローズします。
