### ISSUE TITLE
Enju仮想マシン作成用のレポジトリ作ってもいいんじゃないの？

### ISSUE THREAD

**Issue by yegusa** [next-l/manual#4]
どこで議論すればいいかわからんので、ここで。

@masao @nabeta @nakamura-akifumi 

作成用のスクリプトの共有みたいなはなしがあったけど、
スクリプトだけじゃなくって、
issuを登録したいこともありそうだし（提案とかさ）
Enju仮想マシン作成用のレポジトリ例えば next-l/ VM とか？をつくるってのはどうですか？

**Comment by tfjwr** [comment]
Enju仮想マシンの作り方ということですと、Enju配布や各種バージョンに興味ありそうなベンダー向けにも、「next-l/ VM」があってもいいかもしれませんね。
https://github.com/nabeta/enju_leaf/wiki/Virtualmachine
からもリンクなどでつなげ。vagrant fileや、バージョンに影響しそうなシェルスクリプトあたりがポイントのような気もします。（すみません、詳しくないのでなんとなくですが。）タイプとしてはマニュアルの延長という感じでしょうか。

ちなみに、gitではVM化したファイルを単純に置くだけのところはないのでしょうか？
http://www.next-l.jp/?page=VM

> 最新版    Next-L Enju Leaf 1.1.0.rc7 64bit版(zipファイル) （VMware Player 5用） (2013年12月9日作成, 641.7MB, sha1sum: cf67847e1239a00c079f2384bba5972d751872e7)
> http://www.next-l.jp/download/vm/enju_leaf_1.1.0.rc7_vmware_x86.zip

いずれにせよ、オフィシャルな説明付きで、配布できるルートがどこかを起点にできるとEnjuの普及によいかも？
ウェブステッカー（ブログパーツ的なもの）のようなウェブ配布バナー的なものもあってもよろしいかなと。
（私の方ではビジネスとしてウェブステッカーsnsのようなものにも興味がありますが、それはおいときまして）

ちなみにワークショップ後、私の方はまだVirtual BoxをGUIモードでwin8で開くことができず・・・

**Comment by yegusa** [comment]
今のところ、仮想マシンをgit でおけるところは用意してないのですよね。
githubの容量制限ないのなら、そこに置くのはあり？

あと、私のイメージは、シェルスクリプトとちょっとしたマニュアルとissue登録とかができるgitのレポジトリがあるといいなじゃないかなと。
もちろん、容量制限がないのなら、VM化したファイルそのものを置けるならもっといい気がします。

ちなみに、単にリンクをはって説明追加というだけなら

http://www.next-l.jp/download/vm/

ここはだれでも編集可なのでここでやるかんじかなあ。（このwikiはだれでも更新できるので）。

**Comment by yegusa** [comment]
とりあえず、レポジトリは、作ったのでクローズします。
https://github.com/next-l/enju_leaf_vm
