### ISSUE TITLE
マニュアルのトップページのコンテンツがない

### ISSUE THREAD

**Issue by nabeta** [next-l/manual#42]
http://next-l.github.io/  が404を返している。マニュアルへのリンクを追加するかリダイレクトすること。

**Comment by yegusa** [comment]
マニュアルのトップページというか、

http://next-l.github.io/

これのことだよね？

**Comment by nabeta** [comment]
とりあえず404にはならないようにしました。
https://next-l.github.io

このリポジトリのコンテンツを編集すればよいようです。
https://github.com/next-l/next-l.github.io

**Comment by yegusa** [comment]
htmlを直接いじればいいのかな？

**Comment by nabeta** [comment]
はい、そうです。

**Comment by yegusa** [comment]
とりあえず、リンクつけてみた。pullリクエスト送った。

**Comment by nabeta** [comment]
受け取りました。すでに反映済みです。
https://next-l.github.io

また、manualチームに next-l.github.io リポジトリの読み書きの権限を追加しました。今後は直接 next-l.github.io リポジトリにpushできるはずです。

**Comment by yegusa** [comment]
さっそくありがとうございます。確認しました。
ま、間違えてトップに来た用ってことで、普段は使わないし、これで十分かと。
クローズしますね。

![top2](https://cloud.githubusercontent.com/assets/1328499/3916513/01e9dc62-237c-11e4-8bff-b635bfa696ce.png)
