### ISSUE TITLE
前提としているウインドウサイズを知りたい

### ISSUE THREAD

**Issue by yegusa** [next-l/manual#5]
800x600 ？　
よりも大きそうに思うのですが。

マニュアルのどこかに書きたいと思っているので、教えてください。

ウインドウを小さい幅などにすると微妙につかいずらいレイアウトになるので、
前提としているウインドウサイズってあるんですよね？
→ @nabeta

**Comment by nabeta** [comment]
1024x768としています。

**Comment by yegusa** [comment]
ありがとうございます。どこに書けばいいかなあ。
