### ISSUE TITLE
旧マニュアル（静的HTML）を消しませんか？

### ISSUE THREAD

**Issue by yegusa** [next-l/manual#55]
http://www.next-l.jp/manual/index.html

enju マニュアル

で検索すると、旧マニュアルがトップにきてしまっていて
まぎらわしいです。

消したり、新しい方にリンクはるなりしませんか？

**Comment by masao** [comment]
当該URLへのリンクはすべて新バージョンのトップへのリダイレクト設定を追加しました。

```
RedirectMatch permanent /manual(.*)$ http://next-l.github.io/manual/
```

旧バージョンを確認したいときは、このGithub上の履歴か、Internet Archiveをごらんください。 :smiley:
- http://web.archive.org/http://www.next-l.jp/manual/index.html
- http://web.archive.org/http://www.next-l.jp/manual/Enju_InstallVP_100.html
- http://web.archive.org/http://www.next-l.jp/manual/Enju_Setup_101.html
- http://web.archive.org/http://www.next-l.jp/manual/Enju_Operation_101.html

というので、いかがでしょうか。

**Comment by yegusa** [comment]
ありがとうございます！完璧です！
クローズします。
