### ISSUE TITLE
最初のログインユーザ名の変更：admin → enjuadmin

### ISSUE THREAD

**Issue by masao** [next-l/manual#59]
next-l/enju_leaf#435 を参照のこと。

**Comment by masao** [comment]
rc15以降にインストールしたものは enjuadmin となる。
rc12以前からアップデートしてきたものは admin のまま残る。ただし、Rails4環境ではそのままは動作しない。

**Comment by yegusa** [comment]
#60 と重複

**Comment by yegusa** [comment]
重複のためクローズする
