### ISSUE TITLE
Solr の異体字対応について書く

### ISSUE THREAD

**Issue by scivola** [next-l/manual#64]
https://github.com/next-l/enju_leaf/issues/880
を受けて，インストールマニュアルに追加する Solr の異体字対応の章の下案を作ってみました。

下案なのでプルリクエストでなく Gist に置きました。

https://gist.github.com/scivola/bc61a59c47b72d446c1c

章番号が決められないので，すべて「X」としてあります。

Markdown の初歩は分かりますが，ちょっと書き方が分からなくて適当にしたところがあります。
修正して取り込んでいただくか，あるいはコメントいただければ修正します。
ココは蛇足というコメントも歓迎です。

**Comment by yegusa** [comment]
このマニュアルは画像もないですし、ちょっと開発向けな話でもあるので、
githubのwikiに書いておくほうがよいかもですね。そうすれば、修正が楽ですし。

**Comment by scivola** [comment]
どのようになるのでも構いませんので（ボツも含め），決めていただければと思います。
私の作業が必要であれば具体的にご指示ください。能力的・時間的に可能なことならばそのようにいたします。

**Comment by yegusa** [comment]
すみません、どこにいれるか検討する時間が取れてません、もう少しお待ちください。どっかに入れたいとは思っています。

**Comment by yegusa** [comment]
まずは、インストールマニュアルの6章にほぞそのまま追加しておきました。
https://next-l.github.io/manual/enju_install_vm_6.html

**Comment by scivola** [comment]
ありがとうございました。
ひとまずクローズでいいですよね。判断お願いします。

**Comment by masao** [comment]
全体に少しだけ手を入れましたが、とてもよい内容ができたと思います。ひとまずクローズします。
