### ISSUE TITLE
スタイルを整える

### ISSUE THREAD

**Issue by scivola** [next-l/manual#65]
現状，読みづらいです。文字が小さすぎ，スペーシングも適切とは言いかねます。
CSS をちょっと修正するだけでも大幅に改善します。

そこで，既存の CSS ファイルには手を加えず，追加するだけでスタイルを改善する小さな CSS ファイルを提案します。Gist に置きました。

https://gist.github.com/scivola/ae1a5a14d26ae12f5dc0

HTML レイアウトファイルの CSS 読み込みの一番最後に

``` html
    <link href="path/to/enju-manual-patch.css" rel="stylesheet">
```

を加えていただければ反映されます（パスは正しく書き直す）。

暫定措置として取り込みを検討してください。

最終的にはもう少し根本的な修正（HTML のほうも修正）が必要になると思います。どうも Bootstrap の正しいマークアップが出来ていないようですし。

**Comment by masao** [comment]
ありがとうございます！ひとまず取り込んでみました。

**Comment by yegusa** [comment]
ありがとうございます。よさそうに思います。

**Comment by scivola** [comment]
これ，自分（起票者）で閉じればいいのか。
クローズします。ありがとうございました。
