### ISSUE TITLE
トップページに余計な </script>

### ISSUE THREAD

**Issue by scivola** [next-l/manual#66]
トップページの HTML に余計な `</script>` が入ってます。

下記において 75 行目と 76 行目がひっくり返っているのが原因と思われます。
https://github.com/next-l/manual/blob/gh-pages/_includes/themes/twitter/default.html

プルリク作るほどでもないので，お願いします。

あと，63 行目の

```
language="JavaScript" type="application/javascript"
```

は不要ですね。HTML5 なので。IE6 でもナシでOK。

**Comment by masao** [comment]
ご指摘ありがとうございます。修正しました。

**Comment by scivola** [comment]
HTML5 では`<script>` に `type=text/javascript` は不要なのですが，問題は解決したのでクローズします。
