### ISSUE TITLE
「検索エンジンの設定」に Solr の再インデックスのことを書く

### ISSUE THREAD

**Issue by scivola** [next-l/manual#68]
インストールマニュアル「[6-1-1-4 Enju の再起動](https://next-l.github.io/manual/1.2/enju_install_vm_6.html#section6-1-1-4)」に，マッピングファイルの設定をしたあと Enju を再起動するように書かれているのですが，Solr の再インデックスをしないと書誌情報のほうの変換が行われないようです。

よって，再起動した後，以下の方法で再インデックスするように加筆する必要があると思います。

https://github.com/next-l/enju_leaf/issues/1101#issuecomment-169565236

私がこの章の原稿を書いたとき，再起動だけで OK だと誤解していたので，この記述が抜けました。

**Comment by masao** [comment]
http://next-l.github.io/manual/1.2/enju_install_vm_6.html#section6-1-1-4 記述を追加しました。
